//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICO.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizaciones()
        {
            this.productos_has_cotizaciones = new HashSet<productos_has_cotizaciones>();
            this.ordenes_de_trabajo = new HashSet<ordenes_de_trabajo>();
        }
    
        public int id_cotizacion { get; set; }
        public int folio { get; set; }
        public string nombre_cliente { get; set; }
        public string domicilio_cliente { get; set; }
        public string telefono_cliente { get; set; }
        public decimal costo_cotizacion { get; set; }
        public int anticipo { get; set; }
        public int estado { get; set; }
        public int dias_restantes { get; set; }
        public System.DateTime fecha_cotizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_has_cotizaciones> productos_has_cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenes_de_trabajo> ordenes_de_trabajo { get; set; }
    }
}
