//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICO.modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SicoDBEntities : DbContext
    {
        public SicoDBEntities()
            : base("name=SicoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<cotizaciones> cotizaciones { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<materiales> materiales { get; set; }
        public virtual DbSet<ordenes_de_trabajo> ordenes_de_trabajo { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tipos_de_material> tipos_de_material { get; set; }
        public virtual DbSet<tipos_de_producto> tipos_de_producto { get; set; }
        public virtual DbSet<unidades_de_medida> unidades_de_medida { get; set; }
        public virtual DbSet<materiales_has_compras> materiales_has_compras { get; set; }
        public virtual DbSet<productos_has_cotizaciones> productos_has_cotizaciones { get; set; }
        public virtual DbSet<productos_has_materiales> productos_has_materiales { get; set; }
    }
}
