//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICO.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenes_de_trabajo
    {
        public int id_orden_trabajo { get; set; }
        public int id_cotizacion { get; set; }
        public int folio { get; set; }
        public System.DateTime fecha_orden_trabajo { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public int estado { get; set; }
    
        public virtual cotizaciones cotizaciones { get; set; }
    }
}
